/*!
 * Copyright (c) Microsoft Corporation.
 * All rights reserved. See LICENSE in the project root for license information.
 */

import * as React from 'react';

import { ICampaignbannerData } from './campaignbanner.data';
import { ICampaignbannerProps } from './campaignbanner.props.autogenerated';

export interface ICampaignbannerViewProps extends ICampaignbannerProps<ICampaignbannerData> {}

/**
 *
 * Campaignbanner component
 * @extends {React.PureComponent<ICampaignbannerProps<ICampaignbannerData>>}
 */
class Campaignbanner extends React.PureComponent<ICampaignbannerProps<ICampaignbannerData>> {
    public render(): JSX.Element | null {
        return this.props.renderView(this.props);
    }
}

export default Campaignbanner;
