/*!
 * Copyright (c) Microsoft Corporation.
 * All rights reserved. See LICENSE in the project root for license information.
 */

import * as React from 'react';

import { ISfPaymentMethodData } from './sf-payment-method.data';
import { ISfPaymentMethodProps } from './sf-payment-method.props.autogenerated';

export interface ISfPaymentMethodViewProps extends ISfPaymentMethodProps<ISfPaymentMethodData> {}

/**
 *
 * SfPaymentMethod component
 * @extends {React.PureComponent<ISfPaymentMethodProps<ISfPaymentMethodData>>}
 */
class SfPaymentMethod extends React.PureComponent<ISfPaymentMethodProps<ISfPaymentMethodData>> {
    public render(): JSX.Element | null {
        return this.props.renderView(this.props);
    }
}

export default SfPaymentMethod;
