/*!
 * Copyright (c) Microsoft Corporation.
 * All rights reserved. See LICENSE in the project root for license information.
 */

import * as React from 'react';

import { ICashOnDeliveryData } from './cash-on-delivery.data';
import { ICashOnDeliveryProps } from './cash-on-delivery.props.autogenerated';

export interface ICashOnDeliveryViewProps extends ICashOnDeliveryProps<ICashOnDeliveryData> {}

/**
 *
 * CashOnDelivery component
 * @extends {React.PureComponent<ICashOnDeliveryProps<ICashOnDeliveryData>>}
 */
class CashOnDelivery extends React.PureComponent<ICashOnDeliveryProps<ICashOnDeliveryData>> {
    public render(): JSX.Element | null {
        return this.props.renderView(this.props);
    }
}

export default CashOnDelivery;
