/*!
 * Copyright (c) Microsoft Corporation.
 * All rights reserved. See LICENSE in the project root for license information.
 */

import * as React from 'react';

import { IModalPopupData } from './modal-popup.data';
import { IModalPopupProps } from './modal-popup.props.autogenerated';

export interface IModalPopupViewProps extends IModalPopupProps<IModalPopupData> {}

/**
 *
 * ModalPopup component
 * @extends {React.PureComponent<IModalPopupProps<IModalPopupData>>}
 */
class ModalPopup extends React.PureComponent<IModalPopupProps<IModalPopupData>> {
    public render(): JSX.Element | null {
        return this.props.renderView(this.props);
    }
}

export default ModalPopup;
