/*!
 * Copyright (c) Microsoft Corporation.
 * All rights reserved. See LICENSE in the project root for license information.
 */

import { buildMockModuleProps } from '@msdyn365-commerce/core-internal';
/// <reference types="jest" />

import * as React from 'react';
import * as renderer from 'react-test-renderer';

import ModalPopup from '../modal-popup';
import { IModalPopupData } from '../modal-popup.data';
import { IModalPopupConfig, IModalPopupProps } from '../modal-popup.props.autogenerated';

const mockData: IModalPopupData = {
    actionResponse: {
        text: 'Sample Response Data'
    }
};

const mockConfig: IModalPopupConfig = {
    showText: 'modal-popup'
};

const mockActions = {};

describe('ModalPopup', () => {
    let moduleProps: IModalPopupProps<IModalPopupData>;
    beforeAll(() => {
        moduleProps = buildMockModuleProps(mockData, mockActions, mockConfig) as IModalPopupProps<IModalPopupData>;
    });
    it('renders correctly', () => {
        const component: renderer.ReactTestRenderer = renderer.create(<ModalPopup {...moduleProps} />);
        const tree: renderer.ReactTestRendererJSON | renderer.ReactTestRendererJSON[] | null = component.toJSON();
        expect(tree).toMatchSnapshot();
    });
});
