/*!
 * Copyright (c) Microsoft Corporation.
 * All rights reserved. See LICENSE in the project root for license information.
 */

import * as React from 'react';

import { IOrderTrackingData } from './order-tracking.data';
import { IOrderTrackingProps } from './order-tracking.props.autogenerated';

export interface IOrderTrackingViewProps extends IOrderTrackingProps<IOrderTrackingData> {}

/**
 *
 * OrderTracking component
 * @extends {React.PureComponent<IOrderTrackingProps<IOrderTrackingData>>}
 */
class OrderTracking extends React.PureComponent<IOrderTrackingProps<IOrderTrackingData>> {
    public render(): JSX.Element | null {
        return this.props.renderView(this.props);
    }
}

export default OrderTracking;
